(() => {
  const state = {language:localStorage.getItem("brc.language")||"en",units:localStorage.getItem("brc.units")||"MM",mode:localStorage.getItem("brc.mode")||"od",deferredInstallPrompt:null,lastLogoTap:0};
  const i18n={
    en:{version:"Web Edition 2.1 Beta",build:"Build 2026.06.29.08",input:"Input",result:"Result",units:"Units",thickness:"Thickness",core:"Core Diameter",calculateBy:"Calculate By",turnsShort:"Turns",remainingOD:"Remaining OD",remainingTurns:"Remaining Turns",copyResult:"Copy Result",clearInputs:"Clear",about:"About",note:"Note: Calculations are estimates only.",done:"Done",installApp:"Install App",designed:"Designed and Developed by",copyright:"Copyright © 2026 Raymond Lei",rights:"All Rights Reserved.",legal:"No part of this application, including its design, calculations, source code, documentation, images, or data structure, may be copied, modified, distributed, or reproduced without written permission from Raymond Lei.",installTitle:"Install to Device",installIOS:"Safari → Share → Add to Home Screen",installAndroid:"Chrome → Menu → Install app or Add to Home screen",installDesktop:"Chrome or Edge → Address bar install icon, or Menu → Install app",metric:"Metric",imperial:"Imperial",length:"Length",mm:"MM",inch:"in",ft:"ft",yd:"yd",m:"m",estimatedTurns:"Estimated Turns",estimatedOD:"Estimated OD",copied:"Result copied.",installUnavailable:"Install instructions are shown in About.",easterEggActivated:"BRC logo activated.",warningNumber:"Wrong input: Please enter numbers only.",warningThickness:"Thickness must be greater than 0.",warningCore:"Core Diameter must be greater than 0.",warningPositive:"Remaining value must be greater than 0.",warningODCore:"Remaining OD must be greater than Core Diameter."},
    es:{version:"Edición Web 2.1 Beta",build:"Build 2026.06.29.08",input:"Datos",result:"Resultado",units:"Unidades",thickness:"Espesor",core:"Diámetro del Núcleo",calculateBy:"Calcular Por",turnsShort:"Vueltas",remainingOD:"Diámetro Exterior Restante",remainingTurns:"Vueltas Restantes",copyResult:"Copiar Resultado",clearInputs:"Borrar",about:"Acerca de",note:"Nota: Los cálculos son estimados.",done:"Listo",installApp:"Instalar",designed:"Diseñado y desarrollado por",copyright:"Copyright © 2026 Raymond Lei",rights:"Todos los derechos reservados.",legal:"No part of this application, including its design, calculations, source code, documentation, images, or data structure, may be copied, modified, distributed, or reproduced without written permission from Raymond Lei.",installTitle:"Instalar en dispositivo",installIOS:"Safari → Compartir → Agregar a pantalla de inicio",installAndroid:"Chrome → Menú → Instalar app o Agregar a pantalla de inicio",installDesktop:"Chrome o Edge → Icono de instalación en la barra, o Menú → Instalar app",metric:"Métrico",imperial:"Imperial",length:"Longitud",mm:"MM",inch:"in",ft:"pies",yd:"yardas",m:"m",estimatedTurns:"Vueltas Estimadas",estimatedOD:"Diámetro Exterior Estimado",copied:"Resultado copiado.",installUnavailable:"Las instrucciones de instalación están en Acerca de.",easterEggActivated:"Logo BRC activado.",warningNumber:"Entrada incorrecta: ingrese solo números.",warningThickness:"El espesor debe ser mayor que 0.",warningCore:"El diámetro del núcleo debe ser mayor que 0.",warningPositive:"El valor debe ser mayor que 0.",warningODCore:"El diámetro exterior restante debe ser mayor que el diámetro del núcleo."},
    zh:{version:"网页版 2.1 Beta",build:"Build 2026.06.29.08",input:"输入",result:"结果",units:"单位",thickness:"皮带厚度",core:"卷芯直径",calculateBy:"计算方式",turnsShort:"圈数",remainingOD:"剩余外径",remainingTurns:"剩余圈数",copyResult:"复制结果",clearInputs:"清除",about:"关于",note:"注：计算结果仅为估算。",done:"完成",installApp:"安装应用",designed:"设计与开发",copyright:"版权所有 © 2026 Raymond Lei",rights:"保留所有权利。",legal:"未经 Raymond Lei 书面授权，不得复制、修改、分发、转载本应用程序的设计、计算逻辑、源代码、文档、图片或数据结构。",installTitle:"安装到设备",installIOS:"Safari → 分享 → 添加到主屏幕",installAndroid:"Chrome → 菜单 → 安装应用 或 添加到主屏幕",installDesktop:"Chrome 或 Edge → 地址栏安装图标，或 菜单 → 安装应用",metric:"公制",imperial:"英制",length:"长度",mm:"MM",inch:"英寸",ft:"英尺",yd:"码",m:"米",estimatedTurns:"预估圈数",estimatedOD:"预估外径",copied:"结果已复制。",installUnavailable:"安装说明已显示在 About 页面。",easterEggActivated:"BRC Logo 彩蛋已启动。",warningNumber:"错误：请输入有效数字。",warningThickness:"错误：皮带厚度必须大于 0。",warningCore:"错误：卷芯直径必须大于 0。",warningPositive:"错误：数值必须大于 0。",warningODCore:"错误：剩余外径必须大于卷芯直径。"}
  };
  const $=id=>document.getElementById(id);
  const el={languageSelect:$("languageSelect"),installButton:$("installButton"),thickness:$("thickness"),core:$("core"),remaining:$("remaining"),remainingLabel:$("remainingLabel"),remainingUnit:$("remainingUnit"),warningArea:$("warningArea"),resultArea:$("resultArea"),lengthMMLabel:$("lengthMMLabel"),lengthMLabel:$("lengthMLabel"),lengthInLabel:$("lengthInLabel"),lengthFtLabel:$("lengthFtLabel"),lengthYdLabel:$("lengthYdLabel"),lengthMMValue:$("lengthMMValue"),lengthMValue:$("lengthMValue"),lengthInValue:$("lengthInValue"),lengthFtValue:$("lengthFtValue"),lengthYdValue:$("lengthYdValue"),checkLabel:$("checkLabel"),checkValue:$("checkValue"),toast:$("toast"),aboutModal:$("aboutModal")};
  function t(k){return (i18n[state.language]&&i18n[state.language][k])||i18n.en[k]||k}
  function fmt(v,d=3){const n=Number(v);return n.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:n<10?Math.min(3,d):0})}
  function updateResultLabels(){el.lengthMMLabel.textContent=`${t("length")} (${t("mm")})`;el.lengthMLabel.textContent=`${t("length")} (${t("m")})`;el.lengthInLabel.textContent=`${t("length")} (${t("inch")})`;el.lengthFtLabel.textContent=`${t("length")} (${t("ft")})`;el.lengthYdLabel.textContent=`${t("length")} (${t("yd")})`;el.checkLabel.textContent=state.mode==="od"?t("estimatedTurns"):t("estimatedOD")}
  function setLanguage(l){state.language=l;localStorage.setItem("brc.language",l);el.languageSelect.value=l;document.querySelectorAll("[data-i18n]").forEach(n=>n.textContent=t(n.getAttribute("data-i18n")));updateModeLabels();updateResultLabels();calculate()}
  function setUnits(u){state.units=u;localStorage.setItem("brc.units",u);$("unitMM").classList.toggle("active",u==="MM");$("unitInch").classList.toggle("active",u==="Inch");document.querySelectorAll(".unit-text").forEach(n=>n.textContent=u==="MM"?"mm":"in");updateModeLabels();updateResultLabels();calculate()}
  function setMode(m){state.mode=m;localStorage.setItem("brc.mode",m);$("modeOD").classList.toggle("active",m==="od");$("modeTurns").classList.toggle("active",m==="turns");updateModeLabels();updateResultLabels();calculate()}
  function updateModeLabels(){el.remainingLabel.textContent=state.mode==="od"?t("remainingOD"):t("remainingTurns");el.remainingUnit.textContent=state.mode==="od"?(state.units==="MM"?"mm":"in"):""}
  function num(i){return parseFloat(i.value)}
  function save(){localStorage.setItem("brc.thickness",el.thickness.value);localStorage.setItem("brc.core",el.core.value);localStorage.setItem("brc.remaining",el.remaining.value)}
  function calculate(){save();updateResultLabels();const th=num(el.thickness),co=num(el.core),re=num(el.remaining);el.warningArea.innerHTML="";el.resultArea.style.display="block";let w="";if(Number.isNaN(th)||Number.isNaN(co)||Number.isNaN(re)){if([el.thickness.value,el.core.value,el.remaining.value].some(v=>v!==""))w=t("warningNumber")}else if(th<=0)w=t("warningThickness");else if(co<=0)w=t("warningCore");else if(re<=0)w=t("warningPositive");else if(state.mode==="od"&&re<=co)w=t("warningODCore");if(w){el.warningArea.innerHTML=`<div class="warning">${w}</div>`;el.resultArea.style.display="none";return}if(Number.isNaN(th)||Number.isNaN(co)||Number.isNaN(re)){[el.lengthMMValue,el.lengthMValue,el.lengthInValue,el.lengthFtValue,el.lengthYdValue,el.checkValue].forEach(x=>x.textContent="-");return}let inputLength,check;if(state.mode==="od"){inputLength=Math.PI*(re*re-co*co)/(4*th);check=fmt((re-co)/(2*th),2)}else{inputLength=Math.PI*re*(co+th*(re-1));check=`${fmt(co+2*th*re)} ${state.units}`}const lenIn=state.units==="MM"?inputLength/25.4:inputLength;const lenMM=state.units==="MM"?inputLength:inputLength*25.4;const lenM=lenMM/1000;const lenFt=lenIn/12;const lenYd=lenFt/3;el.lengthMMValue.textContent=fmt(lenMM);el.lengthMValue.textContent=fmt(lenM);el.lengthInValue.textContent=fmt(lenIn);el.lengthFtValue.textContent=fmt(lenFt);el.lengthYdValue.textContent=fmt(lenYd);el.checkValue.textContent=check}
  function clearInputs(){el.thickness.value="";el.core.value="";el.remaining.value="";calculate()}
  function reportText(){return ["Belt Roll Estimate","",`${t("units")}: ${state.units}`,`${t("thickness")}: ${el.thickness.value}`,`${t("core")}: ${el.core.value}`,`${el.remainingLabel.textContent}: ${el.remaining.value}`,"",`${el.lengthMMLabel.textContent}: ${el.lengthMMValue.textContent}`,`${el.lengthMLabel.textContent}: ${el.lengthMValue.textContent}`,`${el.lengthInLabel.textContent}: ${el.lengthInValue.textContent}`,`${el.lengthFtLabel.textContent}: ${el.lengthFtValue.textContent}`,`${el.lengthYdLabel.textContent}: ${el.lengthYdValue.textContent}`,`${el.checkLabel.textContent}: ${el.checkValue.textContent}`].join("\n")}
  async function copyResult(){try{await navigator.clipboard.writeText(reportText())}catch{const ta=document.createElement("textarea");ta.value=reportText();document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove()}showToast(t("copied"))}
  function showToast(m){el.toast.textContent=m;el.toast.style.display="block";setTimeout(()=>el.toast.style.display="none",1800)}
  function openAbout(){el.aboutModal.classList.add("open");el.aboutModal.setAttribute("aria-hidden","false")}
  function closeAbout(){el.aboutModal.classList.remove("open");el.aboutModal.setAttribute("aria-hidden","true")}
  async function installApp(){if(state.deferredInstallPrompt){state.deferredInstallPrompt.prompt();await state.deferredInstallPrompt.userChoice;state.deferredInstallPrompt=null;return}openAbout();const card=$("installInstructions");if(card){card.classList.add("highlight");setTimeout(()=>card.classList.remove("highlight"),2500)}showToast(t("installUnavailable"))}
  function runLogoEasterEgg(){const logo=$("aboutLogo");if(!logo)return;logo.classList.remove("easter-egg");void logo.offsetWidth;logo.classList.add("easter-egg");showToast(t("easterEggActivated"));setTimeout(()=>logo.classList.remove("easter-egg"),5200)}
  function restore(){el.thickness.value=localStorage.getItem("brc.thickness")||"1";el.core.value=localStorage.getItem("brc.core")||"100";el.remaining.value=localStorage.getItem("brc.remaining")||"102"}
  function bind(){el.languageSelect.addEventListener("change",e=>setLanguage(e.target.value));document.querySelectorAll("[data-unit]").forEach(b=>b.addEventListener("click",()=>setUnits(b.getAttribute("data-unit"))));document.querySelectorAll("[data-mode]").forEach(b=>b.addEventListener("click",()=>setMode(b.getAttribute("data-mode"))));[el.thickness,el.core,el.remaining].forEach(i=>{i.addEventListener("input",calculate);i.addEventListener("focus",()=>i.select())});$("copyButton").addEventListener("click",copyResult);$("clearButton").addEventListener("click",clearInputs);$("aboutButton").addEventListener("click",openAbout);$("closeAboutButton").addEventListener("click",closeAbout);el.installButton.addEventListener("click",installApp);const logo=$("aboutLogo");if(logo){logo.addEventListener("dblclick",runLogoEasterEgg);logo.addEventListener("click",()=>{const now=Date.now();if(now-state.lastLogoTap<450)runLogoEasterEgg();state.lastLogoTap=now})}el.aboutModal.addEventListener("click",e=>{if(e.target===el.aboutModal)closeAbout()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeAbout()});window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredInstallPrompt=e})}
  function register(){if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}}
  bind();restore();setUnits(state.units);setMode(state.mode);setLanguage(state.language);register();
})();