const CONFIG_KEY='brc_supabase_config';
const DEVICE_KEY='brc_device_id';
const DIRTY_KEY='brc_cloud_dirty';
let client=null, channel=null, reloadTimer=0, applying=false;
const deviceId=localStorage.getItem(DEVICE_KEY)||crypto.randomUUID();
localStorage.setItem(DEVICE_KEY,deviceId);
const cfg=()=>{try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')}catch{return {}}};
const state={status:'not-configured',user:null,profile:null,lastSync:'',error:''};
const markDirty=()=>localStorage.setItem(DIRTY_KEY,'1');
const clearDirty=()=>localStorage.removeItem(DIRTY_KEY);
const isDirty=()=>localStorage.getItem(DIRTY_KEY)==='1';
function emit(){window.dispatchEvent(new CustomEvent('brc-cloud-state',{detail:{...state}}))}
function setState(p){Object.assign(state,p);emit()}
function configured(){const c=cfg();return /^https:\/\/.+\.supabase\.co$/.test(c.url||'')&&String(c.key||'').startsWith('sb_publishable_')}
function initClient(){if(!configured()||!window.supabase){setState({status:configured()?'library-error':'not-configured'});return null}const c=cfg();client=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return client}
function saveConfig(url,key){localStorage.setItem(CONFIG_KEY,JSON.stringify({url:String(url).trim().replace(/\/$/,''),key:String(key).trim()}));location.reload()}
function clearConfig(){localStorage.removeItem(CONFIG_KEY);location.reload()}
async function signIn(email,password){if(!client)throw new Error('Cloud is not configured.');setState({status:'connecting',error:''});const {error}=await client.auth.signInWithPassword({email,password});if(error){setState({status:'error',error:error.message});throw error}await start()}
async function signOut(){if(client)await client.auth.signOut();stopRealtime();setState({status:'signed-out',user:null,profile:null})}
async function getDefaultLocation(){let {data,error}=await client.from('locations').select('id,location_code,name').eq('location_code','DEFAULT').maybeSingle();if(error)throw error;if(!data){const r=await client.from('locations').insert({location_code:'DEFAULT',name:'Default Location',description:'Initial location'}).select().single();if(r.error)throw r.error;data=r.data}return data}
function mapCloud(rows,txns,profiles){const belts=(rows||[]).map(r=>({id:r.belt_id,cloudId:r.belt_id,balanceId:r.id,name:r.belt_catalog?.description||r.belt_catalog?.belt_code||'Unnamed',part:r.belt_catalog?.belt_code||'',manufacturer:r.belt_catalog?.manufacturer||'',width:Number(r.belt_catalog?.width_mm||0),thickness:Number(r.belt_catalog?.thickness_mm||0),color:r.belt_catalog?.color||'',application:r.belt_catalog?.supplier||'',coreDiameter:0,stock:Number(r.quantity||0),minStock:Number(r.belt_catalog?.minimum_stock||0),location:r.locations?.location_code||'DEFAULT',notes:r.belt_catalog?.notes||'',modified:r.updated_at||r.belt_catalog?.updated_at||new Date().toISOString()}));
 const pmap=Object.fromEntries((profiles||[]).map(p=>[p.id,p.display_name]));
 const history=(txns||[]).map(t=>({id:t.id,date:t.created_at,beltId:t.belt_id,belt:t.belt_catalog?.description||t.belt_catalog?.belt_code||'',part:t.belt_catalog?.belt_code||'',action:t.transaction_type==='set_balance'?'set':t.transaction_type,amount:Math.abs(Number(t.quantity_change||0)),before:Number(t.quantity_before||0),after:Number(t.quantity_after||0),user:pmap[t.performed_by]||'Cloud User',note:t.notes||'',protected:true}));
 return {belts,history};}
async function loadCloud(){if(!client||!state.user)return;setState({status:'syncing',error:''});const local=window.BRCApp?.getData?.()||{belts:[]};const [b,t,p]=await Promise.all([
 client.from('inventory_balances').select('id,belt_id,location_id,quantity,updated_at,belt_catalog(id,belt_code,description,manufacturer,width_mm,thickness_mm,color,supplier,minimum_stock,notes,updated_at),locations(id,location_code,name)').order('updated_at',{ascending:false}),
 client.from('inventory_transactions').select('id,belt_id,location_id,transaction_type,quantity_change,quantity_before,quantity_after,notes,performed_by,created_at,belt_catalog(belt_code,description)').order('created_at',{ascending:true}).limit(2000),
 client.from('profiles').select('id,display_name,role,is_active,can_add_belt,can_modify_belt,can_delete_belt,can_add_stock,can_use_stock,can_set_balance,can_manage_users,can_restore_backup')
 ]);for(const r of [b,t])if(r.error)throw r.error;if(p.error)p.data=[];if(!(b.data||[]).length&&(local.belts||[]).length){setState({status:'migration-needed',lastSync:'',error:''});return}const mapped=mapCloud(b.data,t.data,p.data);applying=true;window.BRCApp?.applyCloudData(mapped);applying=false;setState({status:'connected',lastSync:new Date().toISOString(),error:''})}
async function ensureLocation(code){const c=(code||'DEFAULT').trim()||'DEFAULT';let r=await client.from('locations').select('id').ilike('location_code',c).maybeSingle();if(r.error)throw r.error;if(r.data)return r.data.id;r=await client.from('locations').insert({location_code:c,name:c,created_by:state.user.id,updated_by:state.user.id}).select('id').single();if(r.error)throw r.error;return r.data.id}
async function upsertBelt(b){const code=(b.part||b.id||crypto.randomUUID()).trim();const payload={belt_code:code,description:b.name||code,manufacturer:b.manufacturer||null,width_mm:Number(b.width)||null,thickness_mm:Number(b.thickness)||null,color:b.color||null,supplier:b.application||null,minimum_stock:Number(b.minStock)||0,notes:b.notes||null,is_active:true,updated_by:state.user.id};if(!b.cloudId)payload.created_by=state.user.id;let existing=await client.from('belt_catalog').select('id').ilike('belt_code',code).maybeSingle();if(existing.error)throw existing.error;let r;if(existing.data){r=await client.from('belt_catalog').update(payload).eq('id',existing.data.id).select('id').single()}else{r=await client.from('belt_catalog').insert(payload).select('id').single()}if(r.error)throw r.error;return r.data.id}
async function syncFromLocal(localData,force=false){if(applying||!client||!state.user||(!force&&state.status==='syncing'))return;setState({status:'syncing',error:''});try{const rr=await client.from('inventory_balances').select('quantity,belt_catalog(belt_code),locations(location_code)');if(rr.error)throw rr.error;const remote=new Map((rr.data||[]).map(r=>[`${String(r.belt_catalog?.belt_code||'').toLowerCase()}|${String(r.locations?.location_code||'DEFAULT').toLowerCase()}`,Number(r.quantity||0)]));for(const b of localData.belts||[]){const beltId=await upsertBelt(b);const locationId=await ensureLocation(b.location);const code=(b.part||b.id||'').trim().toLowerCase(),loc=(b.location||'DEFAULT').trim().toLowerCase(),target=Number(b.stock)||0,current=remote.get(`${code}|${loc}`);if(current===undefined||Math.abs(current-target)>1e-9){const {error}=await client.rpc('adjust_inventory',{p_belt_id:beltId,p_location_id:locationId,p_transaction_type:'set_balance',p_amount:target,p_reference:'BRC Web App',p_notes:force?'Initial local inventory upload':'Synchronized from app',p_device_id:deviceId});if(error)throw error}}clearDirty();setState({status:'connected',lastSync:new Date().toISOString(),error:''});if(force)await loadCloud()}catch(e){setState({status:'error',error:e.message||String(e)});throw e}}
async function pushLocalToCloud(){const d=window.BRCApp?.getData?.();if(!d)throw new Error('Local inventory is unavailable.');await syncFromLocal(d,true)}
function scheduleReload(){clearTimeout(reloadTimer);reloadTimer=setTimeout(()=>loadCloud().catch(e=>setState({status:'error',error:e.message})),500)}
function startRealtime(){stopRealtime();channel=client.channel('brc-cloud').on('postgres_changes',{event:'*',schema:'public',table:'belt_catalog'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'inventory_balances'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'inventory_transactions'},scheduleReload).on('postgres_changes',{event:'*',schema:'public',table:'locations'},scheduleReload).subscribe()}
function stopRealtime(){if(channel&&client)client.removeChannel(channel);channel=null}
async function start(){if(!initClient())return;client.auth.onAuthStateChange((_event,session)=>{state.user=session?.user||null;if(!session){setState({status:'signed-out',user:null,profile:null});stopRealtime()}});const {data:{session}}=await client.auth.getSession();if(!session){setState({status:'signed-out',user:null});return}state.user=session.user;const {data:profile,error}=await client.from('profiles').select('*').eq('id',session.user.id).single();if(error){setState({status:'error',error:error.message});return}state.profile=profile;if(!profile.is_active){await signOut();setState({status:'error',error:'This account is inactive.'});return}if(isDirty()){const d=window.BRCApp?.getData?.();if(d)await syncFromLocal(d,false)}await loadCloud();startRealtime()}
window.BRCCloud={state,configured,cfg,saveConfig,clearConfig,signIn,signOut,start,loadCloud,syncFromLocal,pushLocalToCloud,markDirty,isDirty,isApplying:()=>applying};
window.addEventListener('offline',()=>setState({status:'offline',error:''}));window.addEventListener('online',()=>start().catch(e=>setState({status:'error',error:e.message||String(e)})));window.addEventListener('load',()=>navigator.onLine?start().catch(e=>setState({status:'error',error:e.message||String(e)})):setState({status:'offline'}));
