import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const app=read('js/app.js'), cloud=read('js/cloud.js'), css=read('css/app.css'), html=read('index.html'), sw=read('service-worker.js');
test('04.12 metadata',()=>{assert.match(app,/2026\.08\.14\.04\.12/);assert.match(html,/2026\.08\.14\.04\.12/)});
test('permission toggle only uses green when checked',()=>{assert.match(css,/\.permission-switch input:checked\+i\{background:#22c55e\}/)});
test('cloud status semantics are explicit',()=>{assert.match(app,/\['connected','migration-needed'\]/);assert.match(app,/\['error','offline','library-error'\]/)});
test('password reset admin flow exists',()=>{assert.match(app,/cloudPasswordEditor/);assert.match(cloud,/adminResetPassword/);assert.match(cloud,/functions\.invoke\('admin-user'/)});
test('legacy non-UUID local IDs are never used as catalog UUID',()=>{assert.match(cloud,/function isUuid/);assert.match(cloud,/isUuid\(knownId\)/);assert.match(cloud,/Cloud belt record not found/)});
test('inventory transaction enum is guarded',()=>{assert.match(cloud,/Unsupported inventory transaction type/);assert.match(cloud,/set_balance/)});
test('publishable key embedded, secret key absent',()=>{assert.match(cloud,/sb_publishable_bBGvL1QwSX27Eu5bfrERRQ_c9qgziE0/);assert.doesNotMatch(cloud,/sb_secret_/)});
test('beta app code is network-first',()=>{assert.match(sw,/cache:'no-store'/);assert.match(html,/app\.js\?v=202608140412/)});
